name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Rename target
        run: |
          mv target/*.jar target/shortUrl.jar

      # 将 jar 包上传到服务器
      - name: Upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }} # 设置为您的服务器IP地址
          username: ${{ secrets.SSH_USER }} # 设置为您的服务器用户名
          password: ${{ secrets.SSH_PASSWORD }} # 设置为您的服务器密码
          source: 'target/shortUrl.jar'
          target: '/usr/local/yuluo'
          strip_components: 1
      
      - name: 在服务器上执行 java -jar，请确保服务器安装了 JDK
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: | # 命令中的 & 表示在后台运行进程
            cd /usr/local/yuluo
            sh start.sh
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
